// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";

import { Trend } from 'k6/metrics';
import { htmlReport } from "https://raw.githubusercontent.com/benc-uk/k6-reporter/main/dist/bundle.js";
import { textSummary } from "https://jslib.k6.io/k6-summary/0.0.1/index.js";

export let options = {
  stages: [
    { duration: '1m', target: 10 }, // Ramp-up to 10 VUs over 1 minute
    { duration: '2m', target: 10 }, // Stay at 10 VUs for 2 minutes
    { duration: '1m', target: 0 }, // Ramp-down to 0 VUs over 1 minute
  ],
  thresholds: {
    http_req_duration: ['p(95)<500'], // Set a threshold for the response time to be less than 500 milliseconds for 95% of the requests
  },
};
const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    url: "https://reqres.in/api/"
  }
});

export default function() {
  postman[Request]({
    name: "GetUsersList",
    id: "9f5692af-f279-42a9-8b8a-77d9faeb53db",
    method: "GET",
    address: "{{url}}users?page=2",
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "CreateUser",
    id: "0c783faa-e5f3-43ef-a983-d89746d7dc8e",
    method: "POST",
    address: "{{url}}users",
    data: '{\n    "name": "Shivam Rai",\n    "job": "Intern"\n}',
    post(response) {
      pm.test("Status code is 201", function() {
        pm.response.to.have.status(201);
      });
    }
  });

  postman[Request]({
    name: "UpdateUser",
    id: "12452e29-a093-4795-8044-356357e4382d",
    method: "PUT",
    address: "{{url}}users/869",
    data: '{\n    "name": "Shivam",\n    "job": "JavaDeveloper"\n}',
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "PartiallyUpdatUser",
    id: "82ae174f-9fa7-41d6-838b-03b1914c9407",
    method: "PATCH",
    address: "{{url}}users/869",
    data: '{\n    "name": "Shivam Singh"\n}',
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "ReadUser",
    id: "7e51ae47-aebe-49be-9491-87103a7bed97",
    method: "GET",
    address: "{{url}}users?page=2",
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "DeleteUser",
    id: "061eab69-786f-4d91-bd7d-f2f5a30e9b84",
    method: "DELETE",
    address: "{{url}}users/869",
    post(response) {
      pm.test("Status code is 204", function() {
        pm.response.to.have.status(204);
      });
    }
  });
}

  export function handleSummary(data) {
    console.log('HTML Report is generated as result.html')
    return {
      "result.html": htmlReport(data),
      stdout: textSummary(data, { indent: " ", enableColors: true }),
    };
  }